name: commit_actions
run-name: ${{ github.actor }} is building and releasing (to github) the mac,windows,and linux versions of the desktop
on:
  push:
    branches: [ "develop" ]
jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
     - run: flutter config --enable-macos-desktop
     - run: flutter --version    
     - run: flutter pub get
     - run: flutter build macos --no-tree-shake-icons 


#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: |
#        sudo apt-get update -y
#        sudo apt-get install -y ninja-build libgtk-3-dev
#      - run: flutter config --enable-linux-desktop
#      - run: flutter --version    
#      - run: flutter pub get
#      - run: flutter build linux
